apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: production-tls
  namespace: production
spec:
  secretName: production-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - example.com
  - www.example.com
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 720h  # 30 days
